### ISSUE TITLE
ceph_conf_read_file when trying to connect.

### ISSUE THREAD

**Issue by djmoonshine** [ketor/ceph-dokan#6]
This looks like a great project but i can't connect to my cluster.
I read that cephx is not supported yet and and i have dipabled that.
But i get the error ceph_conf_read_file when i try to run ceph-dokan.exe /c c:\temp\ceph.conf  /l n -s and I have tried putting the ceph.conf in the same directory as the exe file and just using the parameters from the example file in the repository but always the same error.
Is the error refering to not being able to read the file at all or is it some parameter error in the file or something else?

**Comment by TelanJ** [comment]
have you edited and saved the file in the windows machine? If so, Ceph.conf must be in the Unix format for it to be read by ceph. I suggest use dos2unix binary executable to convert the file

**Comment by jiffe** [comment]
This can also be fixed by modifying the source to open the file in binary mode so that there isn't a mismatch in byte count

diff --git a/common/ConfUtils.cc b/common/ConfUtils.cc
index 5efde8d..ab87c3f 100644
--- a/common/ConfUtils.cc
+++ b/common/ConfUtils.cc
@@ -98,7 +98,7 @@ parse_file(const std::string &fname, std::dequestd::string *errors,
   int ret = 0;
   size_t sz;
   char *buf = NULL;
-  FILE *fp = fopen(fname.c_str(), "r");
+  FILE *fp = fopen(fname.c_str(), "rb");
   if (!fp) {
     ret = -errno;
     return ret;

**Comment by ksingh7** [comment]
@TelanJ  @jiffe  @ketor 

I have been trying to use ceph-dokan since several days now , but its continuously throwing error
- I have also tried unix2dos to convert ceph.conf but no luck
  ![snap 2015-06-12 at 00 05 44](https://cloud.githubusercontent.com/assets/9701902/8118688/2c3fe500-1099-11e5-98f3-cee76c50c509.png)
- ceph.conf looks like
  ![snap 2015-06-12 at 00 06 38](https://cloud.githubusercontent.com/assets/9701902/8118704/473fb196-1099-11e5-9eab-47eb8913576c.png)
- directory structure
  ![snap 2015-06-12 at 00 06 07](https://cloud.githubusercontent.com/assets/9701902/8118712/502c2b72-1099-11e5-8cc2-18c5cfa6edcd.png)
- Ceph cluster monitor is reachable from this windows host
  ![snap 2015-06-12 at 00 07 14](https://cloud.githubusercontent.com/assets/9701902/8118714/570946be-1099-11e5-89e0-251b5921bca6.png)
- Windows IEUser is a administrator user and the ceph.conf file has full rights. 

Any help in solving this will be really appreciated.

**Comment by jiffe** [comment]
Either of the two previous posts should work.  If you don't want to modify the source, for fread to work in text mode you must have line feeds only as TelanJ says.  It helps to use an editor that can show you extra symbols (such as line feeds and carriage returns) like notepad++.

**Comment by TelanJ** [comment]
@ksingh7 , as I said earlier, It would be easier just to convert the file format rather than editing the source code. Ceph.conf needs to be in a unix format. Use the link below to convert the ceph.conf to a unix format and it should work fine.

http://sourceforge.net/projects/dos2unix/

**Comment by ketor** [comment]
Ceph-dokan only supports UNIX format ceph.conf.

**Comment by ksingh7** [comment]
@jiffe @TelanJ @ketor  Thanks you guys , things are progressing slowly  :+1: 

Now i have a new problem 
- Ceph-dokan.exe works ( reads ceph.conf ) file but it does not mount cephfs as a drive , not it throws any error , please have a look on the screenshot
  ![image](https://cloud.githubusercontent.com/assets/9701902/8138592/e5638ff8-1154-11e5-95e2-95d73db0c1e7.png)
- From windows machine i can reach ceph monitor ( both ping and telnet to 6789 port )
- Do i need to set something on ceph cluster as well ( FYI MDS is active and running on ceph cluster ) any thing else need to be done on ceph side.

Please advice.

**Comment by ksingh7** [comment]
FYI , i have a linux host that can mount CephFS without any problem. So MDS is working perfectly fine.

**Comment by ksingh7** [comment]
@jiffe @TelanJ @ketor @jiffe  guys i would feel lucky , i get some help with this issue :)

**Comment by ksingh7** [comment]
@jiffe @TelanJ @ketor Any help would be appreciated.

**Comment by ketor** [comment]
@ksingh7 finally get ceph-dokan works with all auth=none.
@jiffe would you please give me a pull request?

**Comment by ksingh7** [comment]
@ketor thanks for your much needed help .... Ceph-dokan works like charm.

**Comment by cecarmello** [comment]
My ceph cluster was deployed with all auth = cephx.
The ceph cluster version is Hammer 0.94.6
I made the ceph-dokan.exe . 
When I execute:  ceph-dokan -c ceph.conf -l m, i got:
ceph_conf_read_file OK

..but after some minutes return  signal 88 (core dump)
 if I check netsat output commnad, I can see: local address - foreign address:6789 - states TIME_WAIT

so.. I could not have my drive mounted.  What I need to do ..

tks in advance
